### ISSUE TITLE
Module overwrites local state in generate mode

### ISSUE THREAD

**Issue by bdrtsky** [nuxt-community/universal-storage-module#75]
When in development everything works perfectly. But after I build app with `npm run generate` it ignores local state and overwrite it with `initialState`.

I made reproduction - https://github.com/bdrtsky/universal-module-issue

If you change `theme` in select, then in dev when you refresh the page previous selection preserved, like it's expected. 
But in prod with `generate` `theme` overwritten by `initialState`.

**Comment by pi0** [comment]
Hi @bdrtsky. Thanks for the issue and PR. I think using universal storage for SSG handling is probably not the best way because the SSR version is already rendered with either white or dark. Plugin executes on Client-side which is too late and causes a screen-flash/re-render to change the theme.  Probably it would be better using a sync script to inject `dark` class to the body :)
